[package]
name = "concord-protocol-wasm"
version = "0.1.0"
authors = ["Sam Ternent <hello@ternent.dev>"]
description = "Concord protocol core implemented in Rust and compiled to WebAssembly."
license = "MIT/Apache-2.0"
repository = "https://github.com/samternent/home/packages/concord-protocol-wasm"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
sha2 = "0.10"
serde_json = "1.0"
