name: Release concord.ternent.dev
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_CONCORD_PROJECT_ID }}
  VITE_ISSUER_PUBLIC_KEY_PEM: ${{ secrets.VITE_ISSUER_PUBLIC_KEY_PEM }}
  PNPM_CACHE_PATH: ~/.pnpm-store
  PNPM_CACHE_NAME: pnpm-store-cache
on:
  push:
    tags:
      - "concord-[0-9]+.[0-9]+.[0-9]+"

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Ensure system PATH
        run: echo "/usr/bin:/bin" >> $GITHUB_PATH

      - name: Cache PNPM store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build rust libs
        run: cd packages/concord-protocol-wasm && pnpm build && cd ../..

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Build libs
        run: pnpm build:libs

      - name: Link Vercel project
        run: vercel link --yes --cwd ${{ github.workspace }}/apps/concord --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --cwd ${{ github.workspace }}/apps/concord --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Vercel Environment Information
        run: vercel build --prod --cwd ${{ github.workspace }}/apps/concord --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --cwd ${{ github.workspace }}/apps/concord --token=${{ secrets.VERCEL_TOKEN }}

      - name: Update app version in Redis
        run: node .ops/update-redis-version.mjs
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_ENDPOINT_URI: ${{ secrets.REDIS_ENDPOINT_URI }}
